### ISSUE TITLE
Downloading Sample Tutorial

### ISSUE THREAD

**Issue by ilanaj** [paoyangchen-laboratory/methgo#3]
Hello. I have been unable to download the tutorial (located here: http://paoyang.ipmb.sinica.edu.tw/~gattaca/methgo_demo.tar.gz). It seems that the file is not there. When I either open the link in a browser or view the file downloaded with curl, you get:

Not Found
The requested URL /~gattaca/methgo_demo.tar.gz was not found on this server.
Apache/2.2.22 (Debian) Server at paoyang.ipmb.sinica.edu.tw Port 80

Has the tarball been moved somewhere else?

Thank you!

**Comment by wwliao** [comment]
We've moved the sample data to [this link](http://paoyang.ipmb.sinica.edu.tw/public_data/methgo_demo.tar.gz).

**Comment by ilanaj** [comment]
Great. Thanks!
