### ISSUE TITLE
The chromosome order of whole genome plot is not right

### ISSUE THREAD

**Issue by ubs717** [paoyangchen-laboratory/methgo#4]
Hi, 
I produced a whole genome plot from -MET module and found that the order of chromosome is not right, which showed as 1, 10, 2,....
I tried to sort the CGmap based on the chromosome number but didn't help.
What should I do?

Best,
Shu-Yun

**Comment by wwliao** [comment]
I've changed the sorting algorithm to alphanum (http://www.davekoelle.com/alphanum.html). Could you please download the latest source code and try again?
