### ISSUE TITLE
Drawing error with met module

### ISSUE THREAD

**Issue by cacophrene** [paoyangchen-laboratory/methgo#5]
Hi,

When using the demo files from `paoyang.ipmb.sinica.edu.tw` or my own datasets I can successfully run **methgo cov** but then I get an error ([methgo.met.log.txt](https://github.com/paoyangchen-laboratory/methgo/files/1087906/methgo.met.log.txt)) when running **methgo met**:
`methgo met genes.gtf genome.fa demo.CGmap`

Files `demo.bulk.hist.png` and `demo.bulk.mean.png` are produced, although the second one shows only one color for the three C contexts. 
![demo bulk hist](https://user-images.githubusercontent.com/949552/27329818-f09d0fd4-55ae-11e7-81c1-e7ab7f775d8f.png)
![demo bulk mean](https://user-images.githubusercontent.com/949552/27329822-f38c9732-55ae-11e7-8baf-e14998192f1a.png)

In case it may help, MethGo was retrieved from **git** using:
`git clone https://github.com/paoyangchen-laboratory/methgo.git`

I am using the following packages:

```
cython 0.25.2
numpy 1.12.1
scipy 0.19.0
matplotlib 2.0.2
pandas 0.20.2
pysam 0.8.0
biopython 1.69
pyfasta 0.5.2
pybedtools 0.6.9
```

Thanks a lot for your help.

Regards.

**Comment by wwliao** [comment]
Looks like a bug in Pandas 0.20.2. If you downgrade Pandas to 0.20.1, everything will be back to normal. Thanks.

**Comment by cacophrene** [comment]
I downgraded to 0.20.1 as suggested:

```
Name: pandas
Version: 0.20.1
Summary: Powerful data structures for data analysis, time series,and statistics
Home-page: http://pandas.pydata.org
Author: The PyData Development Team
AAuthor-email: pydata@googlegroups.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: pytz, python-dateutil, numpy
```
But doing it I get a new error related to pyobject:
[error_Pandas_0.20.1.txt](https://github.com/paoyangchen-laboratory/methgo/files/1091369/error_Pandas_0.20.1.txt)

Does it mean I also need to downgrade other packages such as matplotlib?

Thanks for your time.

**Comment by cacophrene** [comment]
Hi,

Problem solved with a fresh install from Debian packages rather than `pip`. Thanks again.
