### ISSUE TITLE
Problems with met.py 

### ISSUE THREAD

**Issue by RubioB** [paoyangchen-laboratory/methgo#6]
Hi, 
I'm try to use the met.py script to analyse BS-Seq data. I encountered this problem : 
Traceback (most recent call last):
  File "/work/project/methgo/scripts/met/met.py", line 442, in <module>
    main()
  File "/work/project/methgo/scripts/met/met.py", line 410, in main
    cgmap = const_cgmap(ctxstr, args.cgmap, args.depth)
  File "/work/project/methgo/scripts/met/met.py", line 97, in const_cgmap
    pos = int(line[2]) - 1 # Transfer to 0-based
ValueError: invalid literal for int() with base 10: "\x12\x17\x87\xc3\xf1\xff\xfe\x7fm\xff\xd7\xb9\xfc\x7f\xff\x7f\xcb\xf2\xbf\xff\xf3\xbf\xfd\xd9\x96\xe7\x7f\xff\xe7\xff\xf9\xff\xfc\xdf\xff\xf9?\xff[\xfe\xaf\xfe\xff\x96\xff\xad\xff\x8f\
xff\xf7\xbf\xa4%\xf9\xff|'\xeb\x81d[\xf0\x8b\xb6\x95?eO\xf2\x7f\x7f'\xfb\xc6\xe4\xfc\xdf\xff\xf9\x13\xff\xd6\x10\xebo\xe2!q\xc4\xdf\xf3\xc7\xfe=\xc7\x8a\x1fr\x938\xf9\xb6\x9dk^\xc9\xff\xfd\xfdS\xae"

I do not understand what is not working... is it in relation with one of my outputs (CGmap file or gtf file) ?

Thanks a lot for your answer, 

Bernadette

**Comment by wwliao** [comment]
Hi Bernadette,

Looks like the issue is relevant to your CGmap file. Does your CGmap file follow the same format described below:

```
    chr1	G	3000851	CHH	CC	0.1	1	10
    chr1	C	3001624	CHG	CA	0.0	0	9
    chr1	C	3001631	CG	CG	1.0	5	5
```

1. chromosome 
2. nucleotide on Watson (+) strand 
3. position 
4.  context (CG/CHG/CHH) 
5. dinucleotide-context (CA/CC/CG/CT)
6. methylation-level = #_of_C / (#_of_C + #_of_T) 
7. #_of_C (methylated C, the count of reads showing C here) 
8. = #_of_C + #_of_T (all Cytosines, the count of reads showing C or T here)

Thanks,
Wen-Wei

**Comment by RubioB** [comment]
Hi again,

Thanks for your answer. My CGmap file has this format :

SL2.50ch00      C       38208   CHH     CC      0.00    0       1
SL2.50ch00      C       38209   CHH     CT      0.00    0       1
SL2.50ch00      C       38214   CHH     CT      0.00    0       1
SL2.50ch00      C       38220   CHH     CC      0.00    0       1
SL2.50ch00      C       38221   CHH     CT      0.00    0       1
SL2.50ch00      C       38223   CHH     CA      0.00    0       1
SL2.50ch00      C       38232   CHH     CA      0.00    0       1
SL2.50ch00      C       38235   CG      CG      1.00    1       1
SL2.50ch00      C       38238   CG      CG      1.00    1       1
SL2.50ch00      C       38240   CHG     CC      0.00    0       1

It seems to be the same than yours ...
________________________________
De : Wen-Wei Liao <notifications@github.com>
Envoyé : mercredi 7 août 2019 15:38
À : paoyangchen-laboratory/methgo <methgo@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [paoyangchen-laboratory/methgo] Problems with met.py (#6)


Hi Bernadette,

Looks like the issue is relevant to your CGmap file. Does your CGmap file follow the same format described below:

    chr1        G       3000851 CHH     CC      0.1     1       10
    chr1        C       3001624 CHG     CA      0.0     0       9
    chr1        C       3001631 CG      CG      1.0     5       5


  1.  chromosome
  2.  nucleotide on Watson (+) strand
  3.  position
  4.  context (CG/CHG/CHH)
  5.  dinucleotide-context (CA/CC/CG/CT)
  6.  methylation-level = #_of_C / (#_of_C + #_of_T)
  7.  #_of_C (methylated C, the count of reads showing C here)
  8.  = #_of_C + #_of_T (all Cytosines, the count of reads showing C or T here)

Thanks,
Wen-Wei

**Comment by wwliao** [comment]
Would you mind sharing the CGmap or part of the CGmap with me, so I can reproduce the error?
You can send it to wen-wei.liao@wustl.edu

**Comment by RubioB** [comment]
Hi,

I just noticed that my message was not sent last night. Here you have my CGmap file (just for informationI was working with a short piece of data, 10000 reads, to test the different tools).
The reference genome is S. lycopersicum (ITAG2.4 version : ftp://ftp.solgenomics.net/tomato_genome/annotation/ITAG2.4_release/)

I also take the opportunity to ask if it is normal to have only the CHH context represnted on the graph obtained with the COV module ?


Thanks a lot  for your help

**Comment by RubioB** [comment]
I come back to you to find out if you have received the files (we have some messaging problems...) ?

Thanks,

Bernadette

________________________________
De : Wen-Wei Liao <notifications@github.com>
Envoyé : mercredi 7 août 2019 15:56
À : paoyangchen-laboratory/methgo <methgo@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [paoyangchen-laboratory/methgo] Problems with met.py (#6)


Would you mind sharing part of the CGmap with me, so I can reproduce the error?

**Comment by wwliao** [comment]
Could you directly send the file to wen-wei.liao@wustl.edu? I guess you can't attach a file via replying the email sending from GitHub.

Thanks,
Wen-Wei

**Comment by wwliao** [comment]
The error is caused by the gzipped CGmap file. Could you decompress it and try again?

Thanks.

**Comment by RubioB** [comment]
Thank you very much!!! It worked !!!!

I have one last question : I get many graphics for different contexts however I still do not understand why in the coverage distribution of methylation sites, I only have the CHH context that is represented (COV module) ?


________________________________
De : Wen-Wei Liao <notifications@github.com>
Envoyé : jeudi 8 août 2019 17:39
À : paoyangchen-laboratory/methgo <methgo@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [paoyangchen-laboratory/methgo] Problems with met.py (#6)


The error is caused by the gzipped CGmap file. Could you decompress it and try it again?

Thanks.

**Comment by wwliao** [comment]
Here is the same figure except I adjusted the y-axis scale.
The fraction of CG/CHG/CHH covered by the 10000 reads is extremely low, so the CG/CHG/CHH lines sort of run together in the y-axis scale from 0 to 100. 
![WTC cov](https://user-images.githubusercontent.com/926905/62818678-063c5980-bb10-11e9-9712-be7ec4f04a0b.png)

**Comment by RubioB** [comment]
Ok,perfect !
Thank you very much for all your help !

Bernadette

________________________________
De : Wen-Wei Liao <notifications@github.com>
Envoyé : samedi 10 août 2019 06:54
À : paoyangchen-laboratory/methgo <methgo@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [paoyangchen-laboratory/methgo] Problems with met.py (#6)


Here is the same figure except I adjusted the y-axis scale.
The fraction of CG/CHG/CHH covered by the 10000 reads is extremely low, so the CG/CHG/CHH lines sort of run together in the y-axis scale from 0 to 100.
[WTC cov]<https://user-images.githubusercontent.com/926905/62818678-063c5980-bb10-11e9-9712-be7ec4f04a0b.png>
